### ISSUE TITLE
orderBy filter expects array

### ISSUE THREAD

**Issue by 10thfloor** [camerondfuller/mission-to-mars-2#1]
You've got an error in your code that is preventing your orderBy filter from working properly ...
<img width="555" alt="screen shot 2016-03-10 at 11 26 50" src="https://cloud.githubusercontent.com/assets/901466/13681653/1bed3bda-e6b3-11e5-8454-ec0cb3a5423b.png">

**Comment by camerondfuller** [comment]
As an object is technically an Array, orderBy accepts it. I understand that it sends out this error because it cannot guarantee the objects order.
